### ISSUE TITLE
Using in objective-c project

### ISSUE THREAD

**Issue by ElKnarzo** [nyris/Nyris.IMX.iOS#2]
Hello,

I would integrate this SDK into an existing project written in Objective-C. After adding the bridging header, the init method of the "CameraManager" class can not be found (see screenshot).

<img width="1230" alt="grafik" src="https://user-images.githubusercontent.com/9089629/60892918-39b16d00-a260-11e9-8644-65746fb0f3a8.png">

How can I use the SDK in an objective-c project?

**Comment by AnasMostefaoui** [comment]
Hi @ElKnarzo 
Unfortunately the SDK was not designed to be compatible with Objective-C and we didn't not test using it with objective-c.

**Comment by sunsided** [comment]
Sadly we don't have Objective-C support on our roadmap anytime soon. I'm closing this ticket.
